"""empty message

Revision ID: 358a7770adca
Revises: 
Create Date: 2020-03-18 16:19:47.374941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358a7770adca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'actor', 'movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actor', type_='foreignkey')
    op.drop_column('actor', 'movie_id')
    # ### end Alembic commands ###
